apps/fanzine/urls.py
from django.conf.urls.defaults import *

urlpatterns = ('fanzine.views',
    url(
        r'^(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)/(?P<slug>\w+)/$',
        'fanzine_details',
        name='fanzine_details',
    )
)

urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.utils.translation import ugettext as _

from django.contrib import admin
admin.autodiscover()

import views

handler500 = "pinax.views.server_error"

from feeds import BlogFeedAll, BlogFeedUser
blogs_feed_dict = {"feed_dict": {
    "all": BlogFeedAll,
    "only": BlogFeedUser,
}}

urlpatterns = patterns("",
    url(r"^$", 'fanzine.views.current_fanzine_details', {
    }, name="home"),
    url(r"^admin/", include(admin.site.urls)),
    url(r'^planet/posts/(?P<post_id>\d+)/$', views.planet_post_detail, name="planet_post_detail"),
    url(r"^planet/", include("planet.urls")),
    #url(r"^fanzine/", include("fanzine.urls")),
    url(
        r'^(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)/(?P<slug>[a-zA-Z0-9-]+)/$',
        'fanzine.views.fanzine_details',
        name='fanzine_details',
    ),
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r"^announcements/", include("announcements.urls")),
    url(r"^account/", include("pinax.apps.account.urls")),
    url(r"^notices/", include("notification.urls")),
    url(r"^comments/", include("threadedcomments.urls")),
    url(r"^i18n/", include("django.conf.urls.i18n")),
    url(r"^announcements/", include("announcements.urls")),
    url(r"^blog/", include("pinax.apps.blog.urls")),
    url(r"^feeds/posts/(.*)/$", "django.contrib.syndication.views.feed", blogs_feed_dict),
)


if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        url(r"", include("staticfiles.urls")),
    )

apps/fanzine/models.py
from django.db import models
from django.db.models import signals
from django.utils.translation import ugettext as _
from django.core import urlresolvers

from tagging.models import Tag

class Fanzine(models.Model):
    date = models.DateTimeField(verbose_name=_(u'publication date'))
    site = models.ForeignKey('sites.site', verbose_name=_(u'site'), default=1)
    slug = models.CharField(max_length=100, verbose_name=_(u'slug'))
    title = models.CharField(max_length=100, verbose_name=_(u'title'), null=True, blank=True)
    text = models.TextField(verbose_name=_(u'editorial'), null=True, blank=True)

    class Meta:
        ordering = ('date',)
        get_latest_by = ('date',)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return urlresolvers.reverse('fanzine_details', kwargs={
            'year': self.date.year,
            'month': self.date.month,
            'day': self.date.day,
            'slug': self.slug
        })

class FanzinePart(models.Model):
    tag = models.ForeignKey('tagging.tag', verbose_name=_(u'tag'))
    fanzine = models.ForeignKey(Fanzine, verbose_name=_(u'fanzine'), null=True, blank=True)
    text = models.TextField(verbose_name=_(u'editorial'), null=True, blank=True)
    order = models.IntegerField(blank=True, null=True)

    class Meta:
        ordering = ('order',)

    def __unicode__(self):
        return self.text

class FanzinePartPost(models.Model):
    part = models.ForeignKey(FanzinePart, verbose_name=_(u'part'))
    post = models.ForeignKey('planet.post', verbose_name=_(u'posts'))
    order = models.IntegerField(blank=True, null=True)

    def save(self, force_insert=False, force_update=False, using=None):
        Tag.objects.add_tag(self.post, self.part.tag)

        return super(FanzinePartPost, self).save(force_insert, force_update, using)

    class Meta:
        ordering = ('order',)

    def __unicode__(self):
        return self.post.title

forms.py
import re

from django import forms
from django.contrib.auth.models import User, Group
from pinax.apps.account.forms import SignupForm
from django.utils.translation import ugettext as _

import utils

class SubscriptionForm(forms.Form):
    email = forms.EmailField()
    infrastructure = forms.BooleanField(widget=forms.CheckboxInput, 
        required=False)

    def clean_email(self):
        value = self.cleaned_data.get('email')
        if User.objects.filter(email=value).count():
            raise forms.ValidationError(_('this email is already subscribed!'))
        return value

    def save(self, request):
        username = re.sub('[^a-zA-Z0-9_]', '', self.cleaned_data.get('email'))
        password = utils.ranpwd()

        while User.objects.filter(username=username):
            username = username + '_'

        signup = SignupForm({
            'username': username,
            'email': self.cleaned_data.get('email'),
            'password1': password,
            'password2': password,
        })

        if not signup.is_valid():
            raise Exception("Signup doesn't validate!")

        user = signup.save()
        group, created = Group.objects.get_or_create(name=u'optin')
        user.groups.add(group)

        return user

apps/fanzine/views.py
from datetime import datetime

from django import http
from django import shortcuts
from django import template

from models import *

def current_fanzine_details(request,
    template_name='fanzine/fanzine_details.html', extra_context=None):

    object = Fanzine.objects.filter(date__lte=datetime.now()).latest()

    context = {
        'object': object,
    }
    context.update(extra_context or {})

    return shortcuts.render_to_response(template_name, context,
        context_instance=template.RequestContext(request))

def fanzine_details(request,
    year, month, day, slug,
    template_name='fanzine/fanzine_details.html', extra_context=None):

    min_datetime = datetime(int(year), int(month), int(day), 0, 0, 0, 0)
    max_datetime = datetime(int(year), int(month), int(day), 23, 59, 59, 0)

    object = shortcuts.get_object_or_404(
        Fanzine, date__gte=min_datetime, date__lte=max_datetime, slug=slug)

    if not request.user.is_staff and object.date > date.today():
        return http.HttpResponseForbidden

    context = {
        'object': object,
    }
    context.update(extra_context or {})

    return shortcuts.render_to_response(template_name, context,
        context_instance=template.RequestContext(request))

views.py
import re

from django import shortcuts
from django import template
from django import http
from django.core import urlresolvers
from django.db import models

from planet import views as planet_views

def planet_post_detail(request, post_id):
    Post = models.get_model('planet', 'post')
    post = shortcuts.get_object_or_404(Post, pk=post_id)

    absolute_url = re.sub('http://[^/]*', '', post.url)

    try:
        result = urlresolvers.resolve(absolute_url)
        return http.HttpResponseRedirect(absolute_url)
    except urlresolvers.Resolver404:
        pass

    return shortcuts.render_to_response("planet/posts/detail.html", {"post": post},
        context_instance=template.RequestContext(request))

def form(request, 
         form_class=None, 
         template_name='form.html', 
         success_url=None,
         success_url_name=None,
         success_message=None,
         extra_context=None):
    if not form_class:
        raise Exception("form_class is a mandatory argument")

    context = {}
    
    print request.session, request.META
    if 'previous_url' not in request.session.keys():
        request.session['previous_url'] = request.META['HTTP_REFERER']

    print request.session['previous_url']

    if request.method == 'POST':
        form = form_class(request.POST)
        if form.is_valid():
            form.save(request)

            if request.user.is_authenticated() and success_message:
                request.user.message_set.create(message=success_message)

            if success_url_name:
                success_url = urlresolvers.reverse(success_url_name)
            if success_url:
                return http.HttpResponseRedirect(success_url)

            if request.session['previous_url']:
                previous_url = request.session.pop('previous_url')
                return http.HttpResponseRedirect(previous_url)
    else:
        form = form_class()

    context['form_class'] = form_class
    context['form'] = form
    context.update(extra_context or {})

    return shortcuts.render_to_response(
        template_name,
        context,
        context_instance=template.RequestContext(request)
    )

apps/fanzine/templates/fanzine/base.html
{% extends "planet/base.html" %}

apps/fanzine/templates/fanzine/fanzine_details.html
{% extends 'fanzine/base.html' %}

{% load i18n %}
{% load markup %}

{% block extrastyle %}
{{ block.super }}
<style type="text/css">
ol.posts {
    margin-left: 0;
}
ol.posts li {
    margin-left: 2em;
    margin-bottom: 0.1em;
    list-style-type: upper-roman;
}
.part h2.title {
    text-align: center;
}
.fanzine_details span.date {
    float: right;
    font-size: 80%;
}
</style>
{% endblock %}

{% block extrameta %}
{{ block.super }}
<meta name="description" content="{{ object.text|capfirst }}" />
<meta name="keywords" content="{% for part in object.fanzinepart_set.all.select_related %}{{ part.tag }},{% endfor %}" />
{% endblock %}

{% block body %}
<div class="fanzine_details">
    <span class="date">
        <a href="{{ object.get_absolute_url }}" title="{{ object.title }}">
        {{ object.date.year }}/{{ object.date.month }}/{{ object.date.day }}
        </a> 
    </span>
    <h1>
        <a href="{{ object.get_absolute_url }}" title="{{ object.title }}">
            {{ object.title|striptags|safe|capfirst }}
        </a>
    </h1>
    <div class="content">
        {{ object.text|capfirst|markdown }}
    </div>
    
    <div class="parts">
    {% for part in object.fanzinepart_set.all.select_related %}
        <div class="part">
            <h2 class="title">
                <a href="{% url planet_tag_detail part.tag.name %}" title="{% trans 'see all posts tagged' %} '{{ part.tag.name }}'">
                    {{ part.tag|capfirst }}
                </a>
            </h2>
            <p class="text">
                {{ part.text|capfirst|markdown }}
            </p>
            <ol class="posts">
            {% for partpost in part.fanzinepartpost_set.all.select_related %}
                <li class="post">
                    <a href="{{ partpost.post.url }}" title="{{ partpost.post.title }} {% trans "posted on" %} {{ partpost.post.feed.title }}">
                        {{ partpost.post.title }}
                    </a>
                </li>
            {% endfor %}
            </ol>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

templates/bl_site_base.html
{% load i18n tagging_tags planet_tags %}
<!doctype html>    

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ --> 
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>      <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>      <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>      <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">

    <!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame 
         Remove this if you use the .htaccess -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>{% block page_title %}{{ site.name }}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="author" content="">

    {% block extrameta %}
    <meta name="DC.title" content="{{ site.name }}" />
    {% endblock %}
    <meta http-equiv="content-language" content="en" />
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8">
    <link href="{{ STATIC_URL }}icons/shortcut.ico" rel="SHORTCUT ICON">
    <link rel="meta" type="application/rdf+xml" title="FOAF" href="{% url planet_foaf %}" /> 
    {% block head_feeds %}
    {% endblock %}
    {% block extrastyle %}{% endblock %}
    {% block extrahead %}{% endblock %}


    <!--  Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Place favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
    <link rel="shortcut icon" href="/favicon.ico">
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">


    <!-- CSS : implied media="all" -->
    <link rel="stylesheet" href="{{ STATIC_URL }}html5boilerplate/css/style.css?v=2">

    <!-- Uncomment if you are specifically targeting less enabled mobile browsers
    <link rel="stylesheet" media="handheld" href="css/handheld.css?v=2">  -->
 
    <!-- All JavaScript at the bottom, except for Modernizr which enables HTML5 elements & feature detects -->
    <script src="{{ STATIC_URL }}html5boilerplate/js/libs/modernizr-1.6.min.js"></script>
    
    <style type="text/css">
#menu {
    float: left;
    width: 200px;
    padding-top: 50px;
    text-align: right;
    border-right: 1px solid black;
    padding-right: 1em;
    margin-right: 1em;
}
#body {
    padding-right: 1em;
    border-right: 1px solid black;
    margin-right: 1em;
    float: left;
}
#email {
}
#main {
    overflow: auto;
}
    </style>

</head>

<body>

    <div id="container">
        <div id="main">
            <div id="menu">
            {% block menu %}
                <h4>{% trans 'Browse' %}</h4>
                <ul>
                    <li>
                        <a href="{% url planet_post_list %}">{% trans 'Posts' %}</a>
                    </li>
                    <li>
                        <a href="{% url planet_author_list %}">{% trans 'Authors' %}</a>
                    </li>
                    <li>
                        <a href="{% url planet_blog_list %}">{% trans 'Blogs' %}</a>
                    </li>
                    <li>
                        <a href="{% url planet_feed_list %}">{% trans 'Feeds' %}</a>
                    </li>
                    <li>
                        <a href="{% url planet_tag_cloud %}">{% trans 'Tag Cloud' %}</a>
                    </li>
                    {% block menu_extra %}
                    {% endblock %}
                </ul>
            {% endblock %}
            </div>

            <div id="body">
            {% block body %}
            {% block content %}
            {% endblock %}
            {% endblock body %}
            </div>

        </div>
    </div> <!--! end of #container -->



                  
    <!-- Javascript at the bottom for fast page loading -->

    <!-- Grab Google CDN's jQuery. fall back to local if necessary -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.js"></script>
    <script>!window.jQuery && document.write(unescape('%3Cscript src="js/libs/jquery-1.4.2.js"%3E%3C/script%3E'))</script>
    
    
    <!-- scripts concatenated and minified via ant build script-->
    <script src="js/plugins.js"></script>
    <script src="js/script.js"></script>
    <!-- end concatenated and minified scripts-->
    
    
    <!--[if lt IE 7 ]>
      <script src="js/libs/dd_belatedpng.js"></script>
      <script> DD_belatedPNG.fix('img, .png_bg'); //fix any <img> or .png_bg background-images </script>
    <![endif]-->

    <!-- yui profiler and profileviewer - remove for production -->
    <script src="js/profiling/yahoo-profiling.min.js"></script>
    <script src="js/profiling/config.js"></script>
    <!-- end profiling code -->


    <!-- asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet 
         change the UA-XXXXX-X to be your site's ID -->
    <script>
     var _gaq = [['_setAccount', 'UA-XXXXX-X'], ['_trackPageview']];
     (function(d, t) {
      var g = d.createElement(t),
          s = d.getElementsByTagName(t)[0];
      g.async = true;
      g.src = ('https:' == location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      s.parentNode.insertBefore(g, s);
     })(document, 'script');
    </script>
 
    <script language="javascript">
        function externalLinks(base_url) {
            return $('a[href^=http]:not("[href^=' + base_url + ']"):not(":has(\'img\')")');
        }
        $(document).ready(function() { externalLinks('{{ site.domain }}').addClass("external"); });
    </script>
    
</body>
</html>

templates/blog/base.html
{% extends "site_base.html" %}

{% load i18n %}

{% block body_class %}blogs{% endblock %}

{% block extra_body %}
{{ block.super }}
<script type="text/javascript" src="{{ STATIC_URL }}pinax/js/comments.js"></script>
<script src="{{ STATIC_URL }}highlight/highlight.pack.js" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function() {
  $('pre code').each(function(i, e) {hljs.highlightBlock(e, '  ')});
});
</script>
<link rel="stylesheet" href="{{ STATIC_URL }}highlight/styles/ir_black.css" />
<style type="text/css">
pre {
    text-align: left;
}
</style>

{% endblock %}


{% block extrahead %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}pinax/css/comments.css" />

<style type="text/css">
.blog-post-meta {
    float: right;
    width: 30%;
    background-color: #e1e1e1;
}
.blog-post-meta p {
    margin: 0;
}
.blog-post-meta img {
    margin: 0;
    float: left;
    padding-right: 1em;
}
.blog-tags img {
    padding-right: 0.3em;
}
</style>
{% endblock %}


{% block subnav %}
    {% if user.is_authenticated %}
        <ul>
            <li><a href="{% url blog_list_all %} ">{% trans "All Blogs" %}</a></li>
            <li><a href="{% url blog_list_yours %}">{% trans "Your Posts" %}</a></li>
            <li><a href="{% url blog_new %}">{% trans "Write a Blog Post" %}</a></li>
        </ul>
    {% else %}
        &nbsp;
    {% endif %}
{% endblock %}

templates/blog/blog_item.html
{% load i18n %}
{% load account_tags %}
{% load markup_tags %}
{% load avatar_tags %}
{% load extra_tagging_tags %}

<div class="blog-post clearfix">
    <h2><a href="{{ blog_post.get_absolute_url }}">{{ blog_post.title }}</a></h2>

    <div class="blog-post-meta">
        {% avatar blog_post.author 50 %}
        <p>
            <b>{% trans "Posted:" %}</b>
            <br />
            {% user_display blog_post.author %}
            <br />
            {{ blog_post.publish|date }}
        </p>
        <div class="blog-tags">
            <p>{% show_tags_for blog_post %}</p>
        </div>
    </div>

    <div class="blog-post-tease">
        {% if blog_post.tease %}
             {% with blog_post.tease as body %}
                {{ body|apply_markup:blog_post.markup }}
            {% endwith %}
        {% else %}
            {% with blog_post.body|truncatewords:"150" as body %}
                {{ body|apply_markup:blog_post.markup }}
            {% endwith %}
        {% endif %}
    </div>

    <div style="clear: both"></div>
</div>

templates/blog/blogs.html
{% extends "blog/base.html" %}

{% load i18n %}
{% load humanize %}
{% load pagination_tags %}
{% load extra_tagging_tags %}
{% load blog_tags %}
{% load markup %}
{% load switchcase %}
{% load restructuredtext %}
{% load blog_tags %}
{% load theme_tags %}

{% block head_title %}{% blocktrans %}All Blogs{% endblocktrans %}{% endblock %}

{% block extra_head %}
    <link rel="alternate" type="application/atom+xml" title="Blog Post Feed for All Users" href="/feeds/posts/all/" />
{% endblock %}

{% block body %}

    <h1>{% trans "All Blogs" %}</h1>

    {% if blogs %}
        {% autopaginate blogs %}

            {% for blog_post in blogs %}
                {% show_blog_post blog_post %}

                {% if request.user.is_staff %}
                <a href="{% url blog_edit blog_post.id %}">
                    {% silk "pencil" %}
                </a>
                {% endif %}

            {% endfor %}

        {% paginate %}

    {% else %}
        {% trans "No blog posts yet." %}
    {% endif %}

{% endblock %}

templates/blog/post.html
{% extends "blog/base.html" %}

{% load i18n %}
{% load humanize %}
{% load account_tags %}
{% load comments_tag %}
{% load tagging_tags %}
{% load blog_tags %}
{% load theme_tags %}
{% load switchcase %}
{% load creole %}
{% load restructuredtext %}
{% load markup %}

{% block head_title %}{% blocktrans %}Blog Post{% endblocktrans %} : {{ post.title }}{% endblock %}

{% block extra_head %}
    <link rel="alternate" type="application/atom+xml" title="Blog Post Feed for All Users" href="/feeds/posts/all/" />
    <link rel="alternate" type="application/atom+xml" title="Blog Post Feed for User {{ post.author.username }}" href="/feeds/posts/only/{{ post.author.username }}/" />
{% endblock %}

{% block body %}
    
    <div class="blog-post">
       
        {% show_blog_post post %}

        <div class="blog-post-body">
        {% switch post.markup %}
            {% case "restructuredtext" %}
                {{ post.body|restructuredtext }}
            {% endcase %}
            {% case "textile" %}
                {{ post.body|textile }}
            {% endcase %}
            {% case "markdown" %}
                {{ post.body|markdown }}
            {% endcase %}
            {% case "creole" %}
                {{ post.body|creole }}
            {% endcase %}
        {% endswitch %}
        </div>

    </div>
    
    <h3>{% trans "Comments" %} :</h3>
    {% comments post %}
{% endblock %}

templates/footer.html
{% load i18n %}
<div class="linklist">
<h3>{% trans "internationnal consulting" %}</h3>
<ul>
    <li>
        <a href="http://gg.ee" title="eZ Publish">
            eZ Publish (ee)
        </a>
    </li>
    <li>
        <a href="http://qafoo.com" title="PHP {% trans "quality expertise" %}">
            PHP {% trans "quality expertise" %} (gr)
        </a>
    </li>
    <li>
        <a href="http://derickrethans.nl" title="PHP {% trans "core development" %}">
            PHP {% trans "core development" %} (nl)
        </a>
    </li>
    <li>
        <a href="http://grenlandweb.no" title="{% trans "norway" %} {% trans "web agency" %}">
            {% trans "web agency" %} (no)
        </a>
    </li>
    <li>
        <a href="http://es.linkedin.com/in/alejandrocapparelli" title="{% trans "communication" %}">
            {% trans "communication" %} (es)
        </a>
    </li>
</ul>
</div>

<div class="linklist">

<h3>{% trans "internationnal partners" %}</h3>
<ul>
    <li>
        <a href="http://fengoffice.com" title="Feng office">
            Feng office (ug)
        </a>
    </li>
    <li>
        <a href="http://paris-offshore.fr" title="{% trans "Offshore and onshore accounting services" %}">
            Paris-Offshore (fr)
        </a>
    </li>
</ul>
</div>

<div class="linklist">
<h3>{% trans "french consulting" %}</h3>
<ul>
    <li>
        <a href="http://emonnerot.chocolatpistache.com/" title="{% trans "computer graphics" %}">
            {% trans "computer graphics" %}
        </a>
    </li>
    <li>
        <a href="http://daxey.net" title="{% trans "development" %}">
            {% trans "development" %}
        </a>
    </li>
    <li>
        <a href="http://pistil-design.net" title="{% trans "marketing" %}">
            {% trans "marketing" %}
        </a>
    </li>
    <li>
        <a href="http://blobidesign.net" title="{% trans "design" %}">
            {% trans "design" %}
        </a>
    </li>
    <li>
        <a href="http://neoskills.net" title="{% trans "system administration" %}">
            {% trans "system administration" %}
        </a>
    </li>
    <li>
        <a href="http://fr.linkedin.com/pub/marc-poussin/3/760/20b" title="{% trans "attorney" %}">
            {% trans "attorney" %}
        </a>
    </li>
</ul>
</div>

<div class="linklist last">
<h3>{% trans "pleasure" %}</h3>
<ul>
    <li>
        <a href="http://idyoulo.com" title="{% trans "world music" %}">
            {% trans "world music" %}
        </a>
    </li>
    <li>
        <a href="http://madeleinemarket.com" title="{% trans "delicatessen" %}">
            {% trans "delicatessen" %}
        </a>
    </li>
    <li>
        <a href="http://www.playlistnow.fm/" title="{% trans "music playlists" %}">
            {% trans "music playlists" %}
        </a>
    </li>
    <li>
        <a href="http://www.prix-litteraires.net/" title="{% trans "literary awards" %}">
            {% trans "literary awards" %}
        </a>
    </li>
    <li>
        <a href="http://chocspace.com" title="{% trans "chocspace" %}">
            chocspace
        </a>
    </li>
</ul>
</div>

templates/form.html
{% extends "planet/base.html" %}

{% load i18n %}
{% load uni_form_tags %}

{% block body %}
<form action="" method="POST" class="uniForm">
    {% csrf_token %}
    {{ form|as_uni_form }}

    <div class="buttonHolder"><button type="submit" class="primaryAction">{% trans "Submit" %}</button></div>
</form>
{% endblock %}

templates/homepage.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block body %}
    
    <h1>{% trans "Welcome to Pinax" %}</h1>
    
    <p>
        {% blocktrans %}
        <b>Pinax</b> is a <a href="http://djangoproject.com/">Django</a>
        project intended to provide a starting point for websites. By
        integrating numerous reusable Django apps to take care of the
        things that many sites have in common, it lets you focus on what
        makes your site different.
        {% endblocktrans %}
    </p>
    
    <p>
        {% blocktrans %}
        For more information about Pinax, see
        <a href="http://pinaxproject.com/">http://pinaxproject.com/</a>.
        {% endblocktrans %}
    </p>
    
    <h2>{% trans "About this project" %}</h2>
    
    <p>
        {% blocktrans %}
        This project lays the foundation for all other Pinax starter projects. It
        provides the project directory layout and some key infrastructure apps on
        which the other starter projects are based.
        {% endblocktrans %}
    </p>
    
{% endblock %}

templates/subscription.html
{% load i18n %}

<div class="box">
    <span class="title">
        {% trans "you found" %}
    </span>
    
    <p>
    {% trans "a source of highly effective information about business and technology directed to IT professionnals whom want to improve their enterprise outcome" %}
    </p>
</div>

<div class="box">
    <span class="title">
        {% trans "we are" %}
    </span>

    <p>
    {% trans "a master mind group of passionnate IT professionnals on a mission: contribute to businesses and lifes" %}
    </p>
</div>

<div class="box">
    <span class="title">
        {% trans "take action" %}
    </span>

    {% if subscription_form_status != 'passed' %}
    <p>
    {% trans "insert your email below to get our free reports and be notified of our latest news" %}
    </p>
    
    <form method="post" action="">
        {% csrf_token %}

        {% if subscription_form_status == 'failed' %}
        <p class="errorField">
            {% trans "your subscription will be saved when the fields are properly filled, thanks for choosing yourlabs.org" %}
        </p>
        {% endif %}

        {% if form.non_field_errors %}
        <div id="errorMsg">
              <ul>
                {{ form.non_field_errors|unordered_list }}
             </ul>
        </div>
        {% endif %}

        <label for="id_email" class="{% if subscription_form.email.errors %}errorField{% endif %}">
            {% trans "Email" %}:
        </label>
        
        <br />

        {% for error in subscription_form.email.errors %}
            <p id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="errorField">
                {{ error }}
            </p>
        {% endfor %}

        {{ subscription_form.email }}

        <br />

        <label for="id_infrastructure">
            {% trans "do you want to be informed about our infrastructure status as well ? server maintenance, new services etc ..." %}
        </label>

        {% for error in subscription_form.infrastructure.errors %}
            <p id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="errorField">
                {{ error }}
            </p>
        {% endfor %}

        {{ subscription_form.infrastructure }}
        
        <input type="hidden" name="subscription_form" value="1" />

        <input type="submit" value="{% trans "subscribe" %}" name="authenticate" />
    </form>

    {% else %}
    <p>
        {% trans "thanks for taking action" %}
    </p>
    {% endif %}
</div>